---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: namespace-user
  namespace: cks
subjects:
  - kind: ServiceAccount
    name: cks-sa
    namespace: cks
roleRef:
  kind: Role
  name: namespace-user
  apiGroup: rbac.authorization.k8s.io
